#!/usr/bin/env python3
import sys
import math

def solve(N: int):
    aa = math.floor(N * 1.08)
    if aa < 206:
        print("Yay!")
    if aa == 206:
        print("so-so")
    if aa > 206:
        print(":(")
    return


# Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
