#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(S: str):
    A = [0] * 26
    a = [0] * 26
    for ss in S:
        if ss.islower():
            a[ord(ss) - ord("a")] += 1
        else:
            A[ord(ss) - ord("A")] += 1
    for AA in A:
        if AA > 1:
            print(NO)
            return
    for aa in a:
        if aa > 1:
            print(NO)
            return
    if sum(A) == 0 or sum(a) == 0:
        print(NO)
        return
    print(YES)

    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
