#!/usr/bin/env python3


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, Q = map(int, input().split())
    S = input()
    idx = 0
    for _ in range(Q):
        t, num = map(int, input().split())
        if t == 1:
            idx += num
            idx %= N
        else:
            num -= 1
            # if num >= idx:
            num -= idx
            print(S[num])
    return



if __name__ == '__main__':
    main()
