#!/usr/bin/env python3


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    H, W = map(int, input().split())
    # C = [[[0] * W for _ in range(H)] for _ in range(26)]
    Cx = [[0] * H for _ in range(26)] # y / x
    Cy = [[0] * W for _ in range(26)] # y / x
    offset_x = [0] * 26
    offset_y = [0] * 26
    for hh in range(H):
        l = input()
        for ww in range(W):
            num = ord(l[ww]) - ord("a")
            Cx[num][hh] += 1  
            Cy[num][ww] += 1
    clearable_x = W
    clearable_y = H
    dx = set()
    dy = set()
    for turn in range(4001):
        clear_x = 0
        clear_y = 0
        for i in range(26):
            offset_tmp_x = 0
            offset_tmp_y = 0
            if clearable_x >= 2:
                for hh in range(H):
                    if hh in dy:
                        continue
                    if Cx[i][hh] - offset_x[i] == clearable_x:
                        clear_y += 1 # ついになる方が影響する # 横1行消えると高さが減る。
                        offset_tmp_y += 1
                        dy.add(hh)
            if clearable_y >= 2:
                for ww in range(W):
                    if ww in dx:
                        continue
                    if Cy[i][ww] - offset_y[i] == clearable_y:
                        clear_x += 1 # ついになる方が影響する
                        offset_tmp_x += 1
                        dx.add(ww)
            offset_x[i] += offset_tmp_x
            offset_y[i] += offset_tmp_y
            # print(i, offset_tmp_x, offset_tmp_y)

        clearable_x -= clear_x
        clearable_y -= clear_y
        # print("offset_x", offset_x[0])
        # print("offset_y", offset_y[0])
        # print(clearable_x)
        # print(clearable_y)
        # print(Cx[0])
        # print(Cy[0])
        # print(dx)
        # print(dy)
        # print("--")
    
    print(H * W - len(dx) * W - len(dy) * H + len(dx) * len(dy))


if __name__ == '__main__':
    main()
