#!/usr/bin/env python3
import sys


def f(i):
    if i % 4 == 0:
        return i
    if i % 4 == 1:
        return 1
    if i % 4 == 3:
        return 0 
    return i + 1
        
def solve(A: int, B: int):
    print(f(B) ^ f(A - 1))
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    solve(A, B)

if __name__ == '__main__':
    main()
