#!/usr/bin/env python3
import sys
from itertools import permutations
import math

def distance(x1, y1, x2, y2):
    return ((x1 - x2) ** 2 + (y1 - y2) ** 2) ** (1/2)

def solve(N: int, x: "List[int]", y: "List[int]"):
    ans = 0
    t = 0
    for order in permutations(range(N)):
        # print(order)
        t += 1
        for i in range(1, N):
            # print(order[i - 1], order[i])
            ans += distance(x[order[i - 1]], y[order[i - 1]], x[order[i]], y[order[i]])
    print(ans / t)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    x = [int()] * (N)  # type: "List[int]"
    y = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        x[i] = int(next(tokens))
        y[i] = int(next(tokens))
    solve(N, x, y)

if __name__ == '__main__':
    main()
