#!/usr/bin/env python3
import sys

# 4 2
# 111100

def solve(a: int, b: int, C: int):
    for aa in range(C):
        for bb in range(C):
            if bin(aa).count("1") == a and bin(bb).count("1") == b and aa ^ bb == C:
                print(a)
                print(b)
                print(C)
                return
    print(-1)
    return





# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    a = int(next(tokens))  # type: int
    b = int(next(tokens))  # type: int
    C = int(next(tokens))  # type: int
    solve(a, b, C)

if __name__ == '__main__':
    main()
