#!/usr/bin/env python3
import sys

def solve(N: int):
    l = []
    for i in range(3 ** N):
        ll = []
        p = i
        for b in range(N):
            p, q = divmod(p, 3)
            if q == 0: # b桁目が0の場合の処理
                ll.append("a")
            elif q == 1: # b桁目が1の場合の処理
                ll.append("b")
            else:
                ll.append("c")
        l.append("".join(ll))
    l.sort()
    print(*l, sep="\n")
    return


# Generated by 2.6.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
