#!/usr/bin/env python3
import sys
import bisect
from collections import defaultdict

def solve(W: int, H: int, N: int, p: "List[int]", q: "List[int]", A: int, a: "List[int]", B: int, b: "List[int]"):
    a = [0] + a + [W]
    b = [0] + b + [H]
    d = defaultdict(int)
    for i in range(N):
        xx, yy = p[i], q[i]
        idx_xx = bisect.bisect_left(a, xx)
        idx_yy = bisect.bisect_left(b, yy)
        d[(idx_xx, idx_yy)] += 1
    # print(d)

    if len(d) == (A + 1) * (B + 1):
        l = sorted(d.values())
        print(l[0], l[-1])
    else:
        l = sorted(d.values())
        print(0, l[-1])

    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    W = int(next(tokens))  # type: int
    H = int(next(tokens))  # type: int
    N = int(next(tokens))  # type: int
    p = [int()] * (N)  # type: "List[int]"
    q = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        p[i] = int(next(tokens))
        q[i] = int(next(tokens))
    A = int(next(tokens))  # type: int
    a = [int(next(tokens)) for _ in range(A)]  # type: "List[int]"
    B = int(next(tokens))  # type: int
    b = [int(next(tokens)) for _ in range(B)]  # type: "List[int]"
    solve(W, H, N, p, q, A, a, B, b)

if __name__ == '__main__':
    main()
