#!/usr/bin/env python3
import sys


def solve(N: int):
    if N == 1:
        print(1)
        return
    l = []
    for i in range(1, N):
        if i * i > N:
            break
        l.append((i, N // i))
        l.append((N // i, i))
    l.sort()
    l = [(0, 0)] + l
    ans = 0
    for i in range(len(l) - 1):
        num1, val1 = l[i]
        num2, val2 = l[i + 1]
        ans += (num2 - num1) * val2
    print(ans)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
