#!/usr/bin/env python3
import sys

def check7(i, base):
    p = i // base
    q = i % base
    if q == 7:
        return False
    if p > 0:
        return check7(p, base)
    return True
    
def solve(N: int):
    count = 0
    for i in range(1, N + 1):
        if check7(i, 10) and check7(i, 8):
            count += 1
    print(count)

    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
