#!/usr/bin/env python3
import sys

def solve(N: int, M: int, A: "List[int]", B: "List[int]", C: "List[int]"):
    INF = 10 ** 16
    ans = 0
    class WarshallFloyd():
        def __init__(self, N):
            self.N = N
            dp = [[INF] * N for _ in range(N)]
            for i in range(N):
                dp[i][i] = 0
            self.dp = dp
        
        # 自己ループを持つグラフの扱いは注意。
        def addEdge(self, fromNode: int, toNode: int, cost: int = 1):
            self.dp[fromNode][toNode] = cost
        
        def build(self):
            nonlocal ans
            """
            やっていることとしては、
            0 〜 (via - 1)までの地点だけを利用して求めたdpテーブルを使い、viaを経由地とした時の更新処理している。
            """
            for via in range(self.N):
                for start in range(self.N):
                    for goal in range(self.N):
                        self.dp[start][goal] = min(self.dp[start][goal], self.dp[start][via] + self.dp[via][goal])
                for start in range(self.N):
                    for goal in range(self.N):
                        if self.dp[start][goal] != INF:
                            ans += self.dp[start][goal]
            return
    wf = WarshallFloyd(N)
    for i in range(M):
        wf.addEdge(A[i] - 1, B[i] - 1, C[i])
    wf.build()
    print(ans)
    return


# Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    A = [int()] * (M)  # type: "List[int]"
    B = [int()] * (M)  # type: "List[int]"
    C = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
        C[i] = int(next(tokens))
    solve(N, M, A, B, C)

if __name__ == '__main__':
    main()
