#!/usr/bin/env python3
import sys


def solve(N: int):
    INF = 10 ** 19
    N = str(N)
    ans = INF
    for i in range(1, 2 ** len(N)):
        tmp = 0
        erase = 0
        for b in range(len(N)):
            if (i >> b) & 1:
                tmp += int(N[b])
            else:
                erase += 1
        if tmp % 3 == 0:
            ans = min(ans, erase)
    print(-1 if ans == INF else ans)
                

    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
