#!/usr/bin/env python3


# Generated by 2.8.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def getDivisors(n: int):
        lowerDivisors, upperDivisors = [], []
        i = 1
        while i * i <= n:
            if n % i == 0:
                lowerDivisors.append(i)
                if i != n // i:
                    upperDivisors.append(n//i)
            i += 1
        return lowerDivisors + upperDivisors[::-1]
    N = int(input())
    A = list(map(int, input().split()))
    nums = [0] * 1001
    for aa in A:
        for i in getDivisors(aa):
            nums[i] += 1
    ans = 0
    mx = 0
    for i in range(2, 1001):
        if nums[i] >= mx:
            ans = i
            mx = nums[i]
    print(ans)

    
    # Failed to predict input format
    pass

if __name__ == '__main__':
    main()
