#!/usr/bin/env python3
import sys
import heapq
INF = 10 ** 16
class Dijkstra():
    def __init__(self, N: int) -> None:
        self.N = N 
        self.G = [[] for _ in range(N)]
        return
    
    # 辺の追加
    def addEdge(self, fromNode: int, toNode: int, cost: int, bothDirection: bool):
        self.G[fromNode].append((cost, toNode))
        if bothDirection:
            self.G[toNode].append((cost, fromNode))
    
    def build(self, startNode: int):
        hq = []
        heapq.heapify(hq)
        # Set start info
        dist = [INF] * self.N
        heapq.heappush(hq, (0, startNode))
        dist[startNode] = 0
        # dijkstra
        while hq:
            min_cost, now = heapq.heappop(hq)
            if min_cost > dist[now]:
                continue
            for cost, next in self.G[now]:
                if dist[next] > dist[now] + cost:
                    dist[next] = dist[now] + cost
                    heapq.heappush(hq, (dist[next], next))
        return dist



def solve(N: int, M: int, H: "List[int]", U: "List[int]", V: "List[int]"):
    dk = Dijkstra(N)
    for uu, vv in zip(U, V):
        d = H[uu - 1] - H[vv - 1]
        if d >= 0:
            dk.addEdge(uu - 1, vv - 1, -d, bothDirection=False)
            dk.addEdge(vv - 1, uu - 1, 2 * d, bothDirection=False)
        else:
            dk.addEdge(uu - 1, vv - 1, -2 * d, bothDirection=False)
            dk.addEdge(vv - 1, uu - 1, d, bothDirection=False)

    ans = dk.build(startNode=0)
    print(-min(ans))
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    H = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    U = [int()] * (M)  # type: "List[int]"
    V = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        U[i] = int(next(tokens))
        V[i] = int(next(tokens))
    solve(N, M, H, U, V)

if __name__ == '__main__':
    main()
