#!/usr/bin/env python3
import sys
from collections import deque
INF = 10 ** 16
def bfs(G: "List[to]", start_node: int) -> list:
    q = deque()
    dist = [INF] * len(G)
    q.append(start_node)
    dist[start_node] = 0
    while q:
        now = q.popleft()
        for next in G[now]:
            if dist[next] != INF:
                continue
            q.append(next)
            dist[next] = dist[now] + 1
    return dist

def solve(N: "List[int]", M: int, a: "List[int]", b: "List[int]"):
    totalN = N[0] + N[1]
    G = [[] for _ in range(totalN)]
    for i in range(M):
        G[a[i] - 1].append(b[i] - 1)
        G[b[i] - 1].append(a[i] - 1)

    d1 = bfs(G, 0)
    d2 = bfs(G, totalN - 1)
    l1 = 0
    for i in range(totalN):
        if d1[i] != INF:
            l1 = max(l1, d1[i])
    l2 = 0
    for i in range(totalN):
        if d2[i] != INF:
            l2 = max(l2, d2[i])
    print(l1 + l2 + 1)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = [int(next(tokens)) for _ in range(2)]  # type: "List[int]"
    M = int(next(tokens))  # type: int
    a = [int()] * (M)  # type: "List[int]"
    b = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        a[i] = int(next(tokens))
        b[i] = int(next(tokens))
    solve(N, M, a, b)

if __name__ == '__main__':
    main()
