#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str

def solve(x: "List[int]", y: "List[int]"):
    x = [0, x[1] - x[0]]
    y = [0, y[1] - y[0]]
    # print(x, y)
    for xx in range(-5, 6):
        for yy in range(-5, 6):
            a = (xx - x[0]) ** 2 + (yy - y[0]) ** 2
            b = (xx - x[1]) ** 2 + (yy - y[1]) ** 2
            if a == b == 5:
                print(YES)
                return
    print(NO)
    return

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    x = [int()] * (2)  # type: "List[int]"
    y = [int()] * (2)  # type: "List[int]"
    for i in range(2):
        x[i] = int(next(tokens))
        y[i] = int(next(tokens))
    solve(x, y)

if __name__ == '__main__':
    main()
