#!/usr/bin/env python3
import sys
import heapq
INF = 10 ** 18 + 1
class Dijkstra():
    def __init__(self, N: int) -> None:
        self.N = N 
        self.G = [[] for _ in range(N)]
        return
    
    # 辺の追加
    def addEdge(self, fromNode: int, toNode: int, cost: int):
        self.G[fromNode].append((cost, toNode))
    
    def build(self, startNode: int):
        hq = []
        heapq.heapify(hq)
        # Set start info
        dist = [INF] * self.N
        heapq.heappush(hq, (0, startNode))
        dist[startNode] = 0
        # dijkstra
        while hq:
            min_cost, now = heapq.heappop(hq)
            if min_cost > dist[now]:
                continue
            for cost, next in self.G[now]:
                if dist[next] > dist[now] + cost:
                    dist[next] = dist[now] + cost
                    heapq.heappush(hq, (dist[next], next))
        return dist

def solve(N: int, M: int, A: "List[int]", B: "List[int]", C: "List[int]"):
    nodes = set(A) | set(B) | set([1]) | set([N])
    compressed = {}
    compressed_to_raw = []
    for index, val in enumerate(sorted(list(nodes))):
        compressed[val] = index
        compressed_to_raw.append(val)
    # print(compressed)
    # print(compressed_to_raw)
    nn = len(compressed_to_raw)
    
    dk = Dijkstra(nn)
    for aa, bb, cc in zip(A, B, C):
        dk.addEdge(compressed[aa], compressed[bb], cc)
        dk.addEdge(compressed[bb], compressed[aa], cc)
    for frm in range(nn - 1):
        d = compressed_to_raw[frm + 1] - compressed_to_raw[frm]
        dk.addEdge(frm, frm + 1, d)
        dk.addEdge(frm + 1, frm, d)
    dist = dk.build(0)
    print(dist[-1])
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    A = [int()] * (M)  # type: "List[int]"
    B = [int()] * (M)  # type: "List[int]"
    C = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
        C[i] = int(next(tokens))
    solve(N, M, A, B, C)

if __name__ == '__main__':
    main()
