#!/usr/bin/env python3
import sys
INF = 10 ** 16
import heapq
class Dijkstra():
    def __init__(self, N: int) -> None:
        self.N = N 
        self.G = [[] for _ in range(N)]
        return
    
    # 辺の追加
    def addEdge(self, fromNode: int, toNode: int, cost: int):
        self.G[fromNode].append((cost, toNode))
        return

    # "toノードに到達するための辺の番号"を同時に持たせることで経路復元時にedge_numを使用できる。
    # def addEdge(self, fromNode: int, toNode: int, cost: int, edge_num: int):
    #     self.G[fromNode].append((cost, toNode, edge_num))
    #     return
    
    def build(self, startNode: int):
        hq = []
        heapq.heapify(hq)
        # Set start info
        dist = [INF] * self.N
        # prev = [-1] * self.N # 経路復元する場合は移動時に直前の頂点や辺を記録して遷移していく。
        heapq.heappush(hq, (0, startNode))
        dist[startNode] = 0
        # dijkstra
        while hq:
            min_cost, now = heapq.heappop(hq)
            if min_cost > dist[now]:
                continue
            for cost, next in self.G[now]:
                if dist[next] > dist[now] + cost:
                    dist[next] = dist[now] + cost
                    # prev[next] = now # 頂点nextに至る直前の頂点(now)または辺(edge_num)を更新。
                    heapq.heappush(hq, (dist[next], next))
        return dist

class BellmanFord():
    def __init__(self, N: int) -> None:
        self.N = N 
        self.E: "list[tuple(int, int, int)]" = []
        return
    
    def addEdge(self, fromNode: int, toNode: int, cost: int):
        self.E.append((fromNode, toNode, cost))
        # print("Really directed Graph?")
        return
    
    def build(self, startNode: int):
        dist = [INF] * self.N
        dist[startNode] = 0
        # 少なくとも頂点数N回だけ全部の辺について最短手数を更新すれば最短経路がもとまる。 O(V * E)
        # N + 1回目に更新が発生するということは閉路があるということなので、そこから到達可能な辺は全て影響を受けることから=INFで潰す。 O(N * E)
        for i in range(self.N * 2):
            for fromNode, toNode, cost in self.E:
                if dist[fromNode] != INF and dist[toNode] > dist[fromNode] + cost:
                    if i >= self.N - 1:
                        dist[toNode] = -INF
                    else:
                        dist[toNode] = dist[fromNode] + cost
        return dist

def solve(N: int, M: int, P: int, A: "List[int]", B: "List[int]", C: "List[int]"):
    # ぽてんしゃるのてすと
    bf = BellmanFord(N)
    for aa, bb, cc in zip(A, B, C):
        bf.addEdge(aa - 1, bb - 1, -cc + P) 
    
    p = bf.build(startNode=0)
    if p[-1] == -INF:
        print(-1)
        return
    if p[-1] >= 0:
        print(0)
        return
    
    dk = Dijkstra(N)
    for aa, bb, cc in zip(A, B, C):
        dk.addEdge(aa - 1, bb - 1, -cc + P + p[aa - 1] - p[bb - 1])
    res = dk.build(0)
    print(-(res[-1] + p[-1] - p[0]))
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    P = int(next(tokens))  # type: int
    A = [int()] * (M)  # type: "List[int]"
    B = [int()] * (M)  # type: "List[int]"
    C = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
        C[i] = int(next(tokens))
    solve(N, M, P, A, B, C)

if __name__ == '__main__':
    main()
