#!/usr/bin/env python3
import sys


def solve(N: int, a: "List[int]"):
    # テーブルの初期化
    maxST = 10 ** 5 + 3
    imos = [0] * (maxST + 1)
    for i in range(N):
        imos[a[i]] += 1
        imos[a[i] + 2 + 1] -= 1

    # ビルド
    for i in range(1, len(imos)):
        imos[i] += imos[i - 1]
    print(max(imos))
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    a = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, a)

if __name__ == '__main__':
    main()
