#!/usr/bin/env python3


# Generated by 2.6.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
from heapq import heapify


def main():
    import heapq
    qq = []
    heapq.heapify(qq)
    Q = int(input())
    sub = [0]
    latestSub = 0
    now = 0
    for _ in range(Q):
        query = input().split()
        if query[0] == "1":
            num = int(query[1])
            heapq.heappush(qq, (num - latestSub, now))
            # print(qq)

        elif query[0] == "2":
            sub.append(int(query[1]) + latestSub)
            latestSub += int(query[1])
            now += 1
            # print(qq)
        else:
            num, time = heapq.heappop(qq)
            # print(qq)
            # print(num, time)
            # print(sub)
            # print(now)
            print(num + latestSub)
    return



if __name__ == '__main__':
    main()
