#!/usr/bin/env python3
import sys

INF = 10 ** 16
MOD = 200  # type: int
YES = "Yes"  # type: str
NO = "No"  # type: str



def solve(N: int, A: "List[int]"):
    l = [i % 200 for i in A]
    nums = [0] * 200
    for i in l:
        nums[i] += 1
    for i in range(200):
        if nums[i] == 0:
            continue
        for a in range(1, i):
            b = i - a
            


    

    return


# Generated by 2.2.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, A)

if __name__ == '__main__':
    main()
