#!/usr/bin/env python3
import sys


def solve(X: int):
    for a in range(130):
        aa = a ** 5
        for b in range(130):
            bb = b ** 5
            if aa - bb == X :
                print(a, b)
                return
            if aa + bb == X:
                print(a, -b)
                return
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    X = int(next(tokens))  # type: int
    solve(X)

if __name__ == '__main__':
    main()
