#!/usr/bin/env python3
import sys


def solve(X: int):
    for a in range(150):
        a5 = a ** 5
        for b in range(150):
            b5 = b ** 5
            for da, db in [(1, 1), (-1, 1), (1, -1)]:
                if a5 * da - b5 * db == X:
                    print(a * da, b * db)
                    return
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    X = int(next(tokens))  # type: int
    solve(X)

if __name__ == '__main__':
    main()
