#!/usr/bin/env python3
import sys


def solve(N: int, T: str):
    dx = 1
    dy = 0
    x, y = 0, 0
    for i in range(N):
        if T[i] == "R":
            if dx == 1:
                dx = 0
                dy = -1
            elif dy == -1:
                dx = -1
                dy = 0
            elif dx == -1:
                dx = 0
                dy = 1
            else: #if dy == 1:
                dx = 1
                dy = 0
        else:
            x += dx
            y += dy
    print(x, y)



    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    T = next(tokens)  # type: str
    solve(N, T)

if __name__ == '__main__':
    main()
