#!/usr/bin/env python3
import sys
import math

def solve(A: int, B: int, C: int):
    g = math.gcd(math.gcd(A, B), C)
    aa = A // g
    bb = B // g
    cc = C // g
    print(aa + bb + cc - 3)
    return


# Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    C = int(next(tokens))  # type: int
    solve(A, B, C)

if __name__ == '__main__':
    main()
