#!/usr/bin/env python3
import sys

MOD = 998244353  # type: int


def solve(N: int, h: "List[int]"):
    nums = [0] * 10 ** 5 + 1
    for hh in h:
        nums[hh] += 1
    
    return


# Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    h = [int(next(tokens)) for _ in range(2 * N)]  # type: "List[int]"
    solve(N, h)

if __name__ == '__main__':
    main()
