#!/usr/bin/env python3
import sys


def solve(N: int, K: int):
    if (N - 1) * (N - 2) // 2 < K:
        print(-1)
        return
    ans = []
    for i in range(1, N):
        ans.append((1, i + 1))
    for i in range(1, N - 1):
        for j in range(i + 1, N):
            if K > 0:
                K -= 1
                continue
            ans.append((i + 1, j + 1))
    print(len(ans))
    for i in ans:
        print(*i)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    solve(N, K)

if __name__ == '__main__':
    main()
