#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str

from collections import defaultdict
class WeightedUnionFind():
    def __init__(self, n):
        self.n = n
        self.group_num = n
        self.parents = [-1] * n # 負で表現したサイズ
        self.diff_weight = [0] * n # 属する集合の親からの距離

    """ 要素xの親を取得。"""
    def find(self, x):
        if self.parents[x] < 0:
            return x
        else:
            r = self.find(self.parents[x]) # 経路圧縮
            self.diff_weight[x] += self.diff_weight[self.parents[x]]; # 累積和をとる
            self.parents[x] = r
            return self.parents[x]

    """ 2つの要素の併合。
    すでに同じ集合に属する場合はFalseを返す。
    """
    def union(self, x, y, w):
        w += self.weight(x)
        w -= self.weight(y)
        x = self.find(x)
        y = self.find(y)

        if x == y:
            return False

        # xの方がサイズが大きい状態にする。parentsは中身負なので注意
        if self.parents[x] > self.parents[y]:
            x, y = y, x
            w = -w

        self.parents[x] += self.parents[y]
        self.parents[y] = x
        self.group_num -= 1
        self.diff_weight[y] = w; 
        return True
    
    def weight(self, x: int) -> int:
        self.find(x) # 経路圧縮
        return self.diff_weight[x]

    def diff(self, x: int, y: int) -> int:
        return self.weight(y) - self.weight(x)

    """ 要素xの属する集合の要素数を取得。"""
    def size(self, x):
        return -self.parents[self.find(x)]

    """ 2つの要素が同一の集合に属するか。"""
    def same(self, x, y):
        return self.find(x) == self.find(y)

    """ 要素xと同一の集合の要素を全取得。
    計算量 : O(N)
    """
    def members(self, x):
        root = self.find(x)
        return [i for i in range(self.n) if self.find(i) == root]

    """ 各集合の根を全取得。
    計算量 : O(N)
    """
    def roots(self):
        return [i for i, x in enumerate(self.parents) if x < 0]

    """ 集合の個数を取得。 v2
    計算量 : O(1)
    """
    def group_count_v2(self):
        return self.group_num

    """ 集合の個数を取得。 v1
    計算量 : O(N)
    """
    def group_count_v1(self):
        return len(self.roots())

    """ 全集合の要素一覧を取得。
    計算量 : O(N)
    """
    def all_group_members(self):
        group_members = defaultdict(list)
        for member in range(self.n):
            group_members[self.find(member)].append((member, self.diff_weight[member]))
        return group_members

    def __str__(self):
        return '\n'.join(f'{r}: {m}' for r, m in self.all_group_members().items())
    

def solve(N: int, M: int, L: "List[int]", R: "List[int]", D: "List[int]"):
    wuf = WeightedUnionFind(N)
    for ll, rr, dd in zip(L, R, D):
        if not wuf.union(ll - 1, rr - 1, dd):
            if wuf.diff(ll - 1, rr - 1) == dd:
                continue
            print(NO)
            return
    print(YES)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    L = [int()] * (M)  # type: "List[int]"
    R = [int()] * (M)  # type: "List[int]"
    D = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        L[i] = int(next(tokens))
        R[i] = int(next(tokens))
        D[i] = int(next(tokens))
    solve(N, M, L, R, D)

if __name__ == '__main__':
    main()
