#!/usr/bin/env python3
import sys
import bisect

def solve(N: int, M: int, A: "List[int]", B: "List[int]"):
    A.sort()
    B.sort()
    ans = 10 ** 16
    for aa in A:
        idx = bisect.bisect_left(B, aa)
        if idx == 0:
            ans = min(ans, abs(B[idx] - aa))
        elif idx == M:
            ans = min(ans, abs(B[idx - 1] - aa))
        else:
            ans = min(ans, abs(B[idx] - aa), abs(B[idx - 1] - aa))
    print(ans)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    B = [int(next(tokens)) for _ in range(M)]  # type: "List[int]"
    solve(N, M, A, B)

if __name__ == '__main__':
    main()
