#!/usr/bin/env python3

YES = "Yes"  # type: str
NO = "No"  # type: str


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, M = map(int, input().split())
    goods = []
    for i in range(N):
        l = list(map(int, input().split()))
        goods.append((l[0], l[1], set(l[2:])))
    for i in range(N):
        for j in range(N):
            if i == j:
                continue
            if goods[i][0] >= goods[j][0] and goods[i][2] <= goods[j][2]:
                if goods[i][0] > goods[j][0]:
                    print(YES)
                    return
                for f in goods[j][2]:
                    if f not in goods[i][2]:
                        print(YES)
                        return
    print(NO)
    return

if __name__ == '__main__':
    main()
