#!/usr/bin/env python3
import sys
from collections import deque

def solve(N: int):
    q = deque()
    q.append((N, 1))
    ans = 0
    while len(q) > 0:
        num, count = q.popleft()
        if num == 1:
            continue
        ans += num * count
        if num % 2 == 0:
            q.append((num // 2, count * 2))
        else:
            q.append((num // 2, count))
            q.append((num // 2 + 1, count))
    print(ans)
    return


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
