#!/usr/bin/env python3

import bisect
INF = 10 ** 9

class BIT:
    def __init__(self, N):
        self.N = N
        self.bit = [0] * (self.N + 1) # 1-indexedのため
        
    def add(self, pos, val):
        '''Add
            O(logN)
            posは0-index。内部で1-indexedに変換される。
            A[pos] += val 
        '''
        i = pos + 1 # convert from 0-index to 1-index
        while i <= self.N:
            self.bit[i] += val
            i += i & -i

    def sum(self, pos):
        ''' Sum
            O(logN)
            posは0-index。内部で1-indexedに変換される。
            Return Sum(A[0], ... , A[pos])
        '''
        res = 0
        i = pos + 1 # convert from 0-index to 1-index
        while i > 0:
            res += self.bit[i]
            i -= i & -i    
        return res
    
    def lowerLeft(self, w):
        '''
        O(logN)
        A0 ~ Aiの和がw以上となる最小のindexを返す。
        '''
        if (w < 0):
            return -1
        x = 0
        k = 1 << (self.N.bit_length() - 1)
        while k > 0:
            if x + k < self.N and self.bit[x + k] < w:
                w -= self.bit[x + k]
                x += k
            k //= 2
        return x

class MultiSet:
    def __init__(self, allVals: "list[int]" ,isSorted: bool = False):
        self.arr = allVals if isSorted else sorted(allVals) #eg. [0, 1, 2, 4] 
        self.bit = BIT(len(allVals)) #eg. [0, 1, 1, 2, 4] 
        self.ammounts = 0
        
    def insert(self, val: int, count: int = 1):
        idx = bisect.bisect_left(self.arr, val)
        self.bit.add(idx, count)
        self.ammounts += count
    
    def delete(self, val: int, count : int = 1):
        k = bisect.bisect_left(self.arr, val)
        self.bit.add(k, -count)
        self.ammounts -= count
    
    def getKth(self, k: int) -> int:
        '''getKth
        k : 0-indexed
        小さい方からK番目の値を取得。
        '''
        return self.arr[self.bit.lowerLeft(k + 1)] if 0 <= k < self.ammounts else -INF
    
    def countLessThanOrEqualTo(self, val: int) -> int:
        '''
        val以下(≦ val)の要素数を返す。
        '''
        # print("#", bisect.bisect_right(self.arr, val))
        return 0 if val < self.arr[0] else self.bit.sum(bisect.bisect_left(self.arr, val))
    
    def countUnder(self, val: int) -> int:
        '''
        val未満(≦ val)の要素数を返す。
        '''
        return 0 if val < self.arr[0] else self.bit.sum(bisect.bisect_left(self.arr, val) - 1) # sum()は負なら0が返るのでvalがarrの最下端の数字でもOK

    def upperBound(self, val: int, k: int) -> int:
        '''upperBound
        | - - - -|-|< - - ->|
                 l u
        valより大きい値において、小さい方からk番目の値を取得
        k: 0-indexed
        (存在しないindexではINFが返る。)
        '''
        return self.getKth(self.countLessThanOrEqualTo(val) + k)

    def lowerBound(self, val: int, k: int) -> int:
        '''upperBound
        | - - - -|<-| - - ->|
                 l u
        valより大きい値において、小さい方からk番目の値を取得
        k: 0-indexed
        (存在しないindexではINFが返る。)
        '''
        return self.getKth(self.countUnder(val) + k)

    def __str__(self):
        res = []
        for i in range(len(self.arr)):
            count = self.bit.sum(i) - (self.bit.sum(i - 1) if i - 1 >= 0 else 0)
            for _ in range(count):
                res.append(i)
        return "[" + ", ".join(f'{v}' for v in res) + "]"
  
# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    Q = int(input())
    queries = []
    numbers = set()
    for _ in range(Q):
        qq = list(map(int, input().split()))
        queries.append(qq)
        numbers.add(qq[1])
    compressed = {}
    compressed_to_raw = []
    for index, val in enumerate(sorted(list(numbers))):
        compressed[val] = index
        compressed_to_raw.append(val)
    tree = MultiSet(list(compressed.values()), False)
    revtree = MultiSet([-i for i in compressed.values()], False)
    for i in range(Q):
        qq = queries[i]
        if qq[0] == 1:
            tree.insert(compressed[qq[1]])
            revtree.insert(-compressed[qq[1]])
        elif qq[0] == 2:
            x, k = qq[1], qq[2]
            ans = revtree.lowerBound(-compressed[x], k - 1)
            print(-1 if ans == -INF else compressed_to_raw[-ans])
            pass
        else:
            x, k = qq[1], qq[2]
            ans = tree.lowerBound(compressed[x], k - 1)
            print(-1 if ans == -INF else compressed_to_raw[ans])
    return

if __name__ == '__main__':
    main()
