#!/usr/bin/env python3
import sys


def solve(N: int):
    ev = 0
    od = 0
    for i in range(1, N + 1):
        if i % 2 == 0:
            ev += 1
        else:
            od += 1
    print(od / (ev + od))
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
