#!/usr/bin/env python3
import sys


def solve(N: int, S: str):
    d = dict()
    ans = set()
    for i in range(N):
        if not S[i] in d.keys():
            d[S[i]] = i
    
    for k, v in d.items():
        dd = dict()
        for i in range(v + 1, N):
            if not S[i] in dd.keys():
                dd[S[i]] = i
        
        for kk, vv in dd.items():
            for i in range(vv + 1, N):
                ans.add(k + kk + S[i])
    print(len(ans))
    return


# Generated by 2.6.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, S)

if __name__ == '__main__':
    main()
