#!/usr/bin/env python3
import sys


def solve(c: "List[List[str]]"):
    c = list(zip(*c[::-1]))
    c = list(zip(*c[::-1]))
    for i in range(len(c)):
        print(*c[i], sep=" ")
    return


# Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    c = [[next(tokens) for _ in range(3 + 1)] for _ in range(3 + 1)]  # type: "List[List[str]]"
    solve(c)

if __name__ == '__main__':
    main()
