#!/usr/bin/env python3
import sys
from itertools import permutations

def solve(N: int):
    S = str(N)
    p = permutations(S)
    ans = 0
    for pp in p:
        for i in range(1, len(S)):
            a = "".join((pp[:i]))
            b = "".join((pp[i:]))
            if a[0] == "0" or b[0] == "0":
                continue
            ans = max(ans, int(a) * int(b))
    print(ans)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
