#!/usr/bin/env python3
import sys
from itertools import permutations

def solve(N: int):
    l = list(str(N))
    ans = 0
    for case in permutations(l):
        for i in range(len(l) - 1):
            ll = list(case)
            a = ll[:i + 1]
            b = ll[i + 1:]
            if a[0] == 0 or b[0] == 0:
                continue
            ans = max(ans, int("".join(a)) * int("".join(b)))
    print(ans)
    return


# Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
