#!/usr/bin/env python3
import sys

def solve(N: int, K: int, a: "List[int]"):
    r = 0
    l = 0
    ans = 0
    sum = 0
    for _ in range(N):
        while r < N and sum < K:
            sum += a[r]
            r += 1
        if sum >= K:
            ans += N - r + 1
            sum -= a[l]
            l += 1
    print(ans)

# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    a = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, K, a)

if __name__ == '__main__':
    main()
