#!/usr/bin/env python3


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    H, W, N, M = map(int, input().split())
    G = [[0] * W for _ in range(H)]
    for _ in range(N):
        A, B = map(int, input().split())
        G[A - 1][B - 1] = 1
    for _ in range(M):
        C, D = map(int, input().split())
        G[C - 1][D - 1] = -1

    
    

    r = [[0] * W for _ in range(H)]
    for hh in range(H):
        cur = 0
        for ww in range(W):
            if G[hh][ww] == 1:
                cur = 1
            elif G[hh][ww] == -1:
                cur = 0
            r[hh][ww] = max(r[hh][ww], cur)
        cur = 0
        for ww in reversed(range(W)):
            if G[hh][ww] == 1:
                cur = 1
            elif G[hh][ww] == -1:
                cur = 0
            r[hh][ww] = max(r[hh][ww], cur)
    for ww in range(W):
        cur = 0
        for hh in range(H):
            if G[hh][ww] == 1:
                cur = 1
            elif G[hh][ww] == -1:
                cur = 0
            r[hh][ww] = max(r[hh][ww], cur)
        cur = 0
        for hh in reversed(range(H)):
            if G[hh][ww] == 1:
                cur = 1
            elif G[hh][ww] == -1:
                cur = 0
            r[hh][ww] = max(r[hh][ww], cur)
    ans = 0
    for hh in range(H):
        ans += sum(r[hh])            
    print(ans)


if __name__ == '__main__':
    main()
