#!/usr/bin/env python3
import sys


def solve(N: int, X: "List[int]"):
    l = sorted(X)
    a, b = l[len(l) // 2 - 1],  l[len(l) // 2]
    if a == b:
        for _ in X:
            print(a)
        return
    for i in X:
        if i <= a:
            print(b)
        else:
            print(a)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    X = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, X)

if __name__ == '__main__':
    main()
