#!/usr/bin/env python3
INF = 10 ** 10

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, M = map(int, input().split())
    A = list(map(int, input().split()))
    B = list(map(int, input().split()))
    # Aのi文字目まで、Bのj文字目までで異なっている文字数
    dp = [[INF] * (M + 1) for _ in range(N + 1)]
    for i in range(N + 1):
        dp[i][0] = i
    for j in range(M + 1):
        dp[0][j] = j
    for i in range(N):
        for j in range(M):
            if A[i] == B[j]:
                dp[i + 1][j + 1] = min(dp[i + 1][j + 1], dp[i][j] + 0)
            dp[i + 1][j + 1] = min(dp[i + 1][j + 1], dp[i + 1][j] + 1, dp[i][j + 1] + 1,  dp[i][j] + 1)
    print(dp[-1][-1])
    return

if __name__ == '__main__':
    main()
