#!/usr/bin/env python3
import sys


def solve(A: int, B: int, C: int):
    if A == B:
        print("Takahashi" if C == 1 else "Aoki")
    else:
        print("Takahashi" if A > B else "Aoki")
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    C = int(next(tokens))  # type: int
    solve(A, B, C)

if __name__ == '__main__':
    main()
