#!/usr/bin/env python3
import sys


def solve(A: str):
    if len(A) > 1:
        print(A[:-1])
        return
    if A == "a":
        print(-1)
        return
    print(chr(ord(A) - 1))
    return


# Generated by 2.6.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = next(tokens)  # type: str
    solve(A)

if __name__ == '__main__':
    main()
