#!/usr/bin/env python3
import sys


def solve(N: int, K: int, C: int, S: str):
    l = set()
    i = 0
    while True:
        if i >= N:
            break
        if S[i] == "o":
            l.add(i + 1)
            i += C + 1
        else:
            i += 1

    r = set()
    i = N - 1
    while True:
        if i < 0:
            break
        if S[i] == "o":
            r.add(i + 1)
            i -= C + 1
        else:
            i -= 1
    ans = sorted(list(l & r))
    if len(ans) > K:
        pass
    else:
        print(*ans, sep="\n")
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    C = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, K, C, S)

if __name__ == '__main__':
    main()
