#!/usr/bin/env python3
import sys
import math

def solve(X: int):
    money = 100
    for year in range(1, 10 ** 6):
        interest = money // 100
        money += interest
        if money >= X:
            print(year)
            return

# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    X = int(next(tokens))  # type: int
    solve(X)

if __name__ == '__main__':
    main()
