#!/usr/bin/env python3
import sys
import heapq
INF = 10 ** 16
class Dijkstra():
    def __init__(self, H: int, W: int, A: "list[list[int]]", B: "list[list[int]]") -> None:
        self.H = H
        self.W = W
        self.A = A
        self.B = B
        return
    
    def build(self, startY: int, startX: int):
        hq = []
        heapq.heapify(hq)
        # Set start info
        dist = [[INF for _ in range(self.W)] for _ in range(self.H)]
        heapq.heappush(hq, (0, startY, startX)) # (cost, y, x)
        dist[startY][startX] = 0
        # dijkstra
        while hq:
            min_cost, nowy, nowx = heapq.heappop(hq)
            if min_cost > dist[nowy][nowx]:
                continue
            for dx, dy in [(1, 0), (-1, 0)]:
                nexty = nowy + dy
                nextx = nowx + dx
                if nexty < 0 or nextx < 0 or nexty >= self.H or nextx >= self.W:
                    continue
                cost = self.A[nexty][nextx - 1]
                if dist[nexty][nextx] > dist[nowy][nowx] + cost:
                    dist[nexty][nextx] = dist[nowy][nowx] + cost
                    heapq.heappush(hq, (dist[nexty][nextx], nexty, nextx))
            for dx, dy in [(0, 1)]:
                nexty = nowy + dy
                nextx = nowx + dx
                if nexty < 0 or nextx < 0 or nexty >= self.H or nextx >= self.W:
                    continue
                cost = self.B[nexty - 1][nextx]
                if dist[nexty][nextx] > dist[nowy][nowx] + cost:
                    dist[nexty][nextx] = dist[nowy][nowx] + cost
                    heapq.heappush(hq, (dist[nexty][nextx], nexty, nextx))
            for i in range(2, nowy + 1):
                nexty = nowy - i
                nextx = nowx
                if nexty < 0 or nextx < 0 or nexty >= self.H or nextx >= self.W:
                    continue
                cost = 1 + i
                if dist[nexty][nextx] > dist[nowy][nowx] + cost:
                    dist[nexty][nextx] = dist[nowy][nowx] + cost
                    heapq.heappush(hq, (dist[nexty][nextx], nexty, nextx))
        return dist

def solve(R: int, C: int, A: "List[List[int]]", B: "List[List[int]]"):
    dk = Dijkstra(R, C, A, B)
    dist = dk.build(0, 0)
    print(dist[-1][-1])
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    R = int(next(tokens))  # type: int
    C = int(next(tokens))  # type: int
    A = [[int(next(tokens)) for _ in range(C - 1)] for _ in range(R)]  # type: "List[List[int]]"
    B = [[int(next(tokens)) for _ in range(C)] for _ in range(R - 1)]  # type: "List[List[int]]"
    solve(R, C, A, B)

if __name__ == '__main__':
    main()
