#!/usr/bin/env python3
import sys

MOD = 1000000007  # type: int


def solve(N: int, K: int, a: "List[int]"):
    if sum(a) < K:
        print(0)
        return
    dp = [[0] * (K) for _ in range(N)]
    sums = [[0] * (K) for _ in range(N)]
    if K == 0:
        print(1)
        return
    dp[0][0] = 1
    for i in range(0, N):   # i人目
        for j in range(0, K):   # j個
            if i == j == 0:
                continue
            for k in range(a[i]): # i人目に配る個数 (0 ~ ai)
                if j - k >= 0:
                    dp[i][j] = (dp[i][j] + dp[i - 1][j - k]) % MOD
    for i in range(N):
        print(dp[i])
    print(dp[N - 1][K - 1])
    # for i in range(K + 1):
    #     print(dp[i])
            
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    a = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, K, a)

if __name__ == '__main__':
    main()
