#!/usr/bin/env python3
import sys
from collections import Counter

YES = "Yes"
NO = "No"

# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    S = input()
    if len(S) <= 2:
        if int(S) % 8 == 0 or int(S[::-1]) % 8 == 0:
            print(YES)
        else:
            print(NO)
    else:
        cs = Counter(S)
        for i in range(112, 1000, 8):
            if not (Counter(str(i)) - cs):
                print(YES)
                break
        else:
            print(NO)
    return

if __name__ == '__main__':
    main()
