#!/usr/bin/env python3
import sys


def solve(N_A: int, N_B: int, A: "List[int]", B: "List[int]"):
    return


# Generated by 2.11.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N_A = int(next(tokens))  # type: int
    N_B = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N_A)]  # type: "List[int]"
    B = [int(next(tokens)) for _ in range(N_B)]  # type: "List[int]"
    solve(N_A, N_B, A, B)

if __name__ == '__main__':
    main()
