#!/usr/bin/env python3
from itertools import accumulate

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N = int(input())
    A = list(map(int, input().split()))
    acc = list(accumulate(A))
    # print(acc)
    max_move = [0]
    for aa in acc:
        max_move.append(max(max_move[-1], aa))
    max_move = max_move[1:]
    # print(max_move)

    cur = 0
    cur_max = 0
    ans = 0
    for i in range(N):
        cur_max = cur + max_move[i]
        cur += acc[i]
        # print(cur)
        # print(cur_max)
        # print("---")
        ans = max(ans, cur_max)
    print(ans)
    return



if __name__ == '__main__':
    main()
