#!/usr/bin/env python3
from collections import defaultdict
import sys


def solve(N: int, M: int, A: "List[int]"):
    d = defaultdict(int)
    for aa in A:
        d[aa] += 1
    mi, ma = min(d.values()) if len(d.keys()) == M else 0, max(d.values())
    print(mi, ma)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, M, A)

if __name__ == '__main__':
    main()
