#!/usr/bin/env python3
import sys


def solve(N: int, S: str):
    f = 0
    ans = []
    for ss in S:
        if ss == '"':
            f += 1
            f %= 2
        if ss == "," and f == 0:
            ans.append(".")
        else:
            ans.append(ss)
    print(*ans, sep="")
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, S)

if __name__ == '__main__':
    main()
