#!/usr/bin/env python3
import sys


def solve(N: int, v_a: int, v_b: int, L: int):
    rest = L
    for _ in range(N):
        sec = rest / v_a
        rest = sec * v_b
    print(rest)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    v_a = int(next(tokens))  # type: int
    v_b = int(next(tokens))  # type: int
    L = int(next(tokens))  # type: int
    solve(N, v_a, v_b, L)

if __name__ == '__main__':
    main()
