#!/usr/bin/env python3
import sys
from itertools import accumulate

MOD = 998244353  # type: int

def solve(N: int, K: int, L: "List[int]", R: "List[int]"):
    dp = [0] * N
    dp[0] = 1
    sdp = [0] + [1] * N
    for i in range(1, N):
        for ll, rr in zip(L, R):
            dp[i] += sdp[max(0, i - ll + 1)] - sdp[max(0, i - rr)]
            dp[i] %= MOD
            sdp[i + 1] = sdp[i] + dp[i]
    print(dp[-1] % MOD)
    # dp = [0] * N
    # dp[0] = 1
    # for i in range(N):
    #     for ll, rr in zip(L, R):
    #         for d in range(ll, rr + 1):
    #             if i - d < 0:
    #                 continue
    #             dp[i] += dp[i - d]
    #             dp[i] %= MOD
    # print(dp)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    L = [int()] * (K)  # type: "List[int]"
    R = [int()] * (K)  # type: "List[int]"
    for i in range(K):
        L[i] = int(next(tokens))
        R[i] = int(next(tokens))
    solve(N, K, L, R)

if __name__ == '__main__':
    main()
