#!/usr/bin/env python3
import sys


def solve(A: int, B: int, C: int):
    A = int(str(A)[-1])
    if A in [0, 1, 5, 6]:
        print(A)
        return
    if A in [4, 9]:
        p = 2
    else:
        p = 4
    bc = pow(B, C, p)
    if bc == 0:
        bc = p
    ans = int(str(pow(A, bc))[-1])
    print(ans)
    return

# 0 0
# 1 1
# 2 4 8 6 2
# 3 9 7 1 3
# 4 6 4
# 5 5
# 6 6
# 7 9 3 1 7
# 8 4 2 6 8
# 9 1 9




# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    C = int(next(tokens))  # type: int
    solve(A, B, C)

if __name__ == '__main__':
    main()
