#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, X: int, a: "List[int]", b: "List[int]"):
    dp = [[0] * (X + 1) for _ in range(N + 1)]
    dp[0][0] = 1
    for i in range(N):
        for k in range(X + 1):
            if dp[i][k]:
                if k + a[i] < X + 1:
                    dp[i + 1][k + a[i]] = 1
                if k + b[i] < X + 1:
                    dp[i + 1][k + b[i]] = 1
    print(YES if dp[-1][X] else NO)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    a = [int()] * (N)  # type: "List[int]"
    b = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        a[i] = int(next(tokens))
        b[i] = int(next(tokens))
    solve(N, X, a, b)

if __name__ == '__main__':
    main()
