#!/usr/bin/env python3
import sys


def solve(N: int, A: "List[int]", B: "List[int]"):
    l = [(2 * aa + bb, aa + bb, aa) for aa, bb in zip(A, B)]
    l.sort(reverse=True)
    sumA = [0]
    sumB = [0]
    for i in range(N):
        sumA.append(sumA[-1] + l[i][1])
    for i in reversed(range(N)):
        sumB.append(sumB[-1] + l[i][2])
    # print(sumA)
    # print(sumB)
        
    # print(l)
    for i in range(N + 1):
        if sumA[i] > sumB[-1 - i]:
            print(i)
            return
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int()] * (N)  # type: "List[int]"
    B = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
    solve(N, A, B)

if __name__ == '__main__':
    main()
