#!/usr/bin/env python3
import sys
from itertools import groupby

def solve(S: str):
    a = [0, 0]
    for i in list(S):
        a[int(i)] += 1
    print(min(a) * 2)
    return


# Generated by 2.8.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
