#!/usr/bin/env python3


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N = int(input())
    l = []
    for i in range(N):
        _ = input()
        s = set(map(int, input().split()))
        l.append(s)
    X = int(input())
    ans = []
    m = 10 ** 16
    for i in range(N):
        if X in l[i]:
            if len(l[i]) == m:
                ans.append(i + 1)
            elif len(l[i]) < m:
                m = len(l[i])
                ans = [i + 1]
    print(len(ans))
    if len(ans) > 0:
        print(*ans)





if __name__ == '__main__':
    main()
