#!/usr/bin/env python3
import sys


def solve(N: int):
    p, q = divmod(N, 5)
    if q <= 2:
        print(p * 5)
    else:
        print((p + 1) * 5)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
