#!/usr/bin/env python3
from collections import defaultdict
import bisect

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    return


if __name__ == '__main__':
    main()
