#!/usr/bin/env python3
import sys

def getDivisors(n: int):
    l = []
    i = 1
    while i * i <= n: # sqrt(N)まで試し割りする。
        if n % i == 0:
            l.append((i, n // i))
        i += 1
    return l


def solve(N: int):
    ans = 10 ** 16
    for x, y in getDivisors(N):
        ans = min(ans, x + y - 2)
    print(ans)
    return
    


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
