#!/usr/bin/env python3
import sys

MOD = 998244353  # type: int


def solve(n: int, m: int, s: int, t: int, u: int):
    return


# Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    n = int(next(tokens))  # type: int
    m = int(next(tokens))  # type: int
    s = int(next(tokens))  # type: int
    t = int(next(tokens))  # type: int
    u = int(next(tokens))  # type: int
    solve(n, m, s, t, u)

if __name__ == '__main__':
    main()
