#!/usr/bin/env python3
import sys

MOD = 1000000007  # type: int
class Combination():
    def __init__(self, factorial_max: int, mod: int) -> None:
        """
        factorial_max = 7.3 * 10 ** 5 : Python limit (>2sec)
        factorial_max = 10 ** 6 : PyPy limit (=260 ~ 280msec)
        
        O(factorial_max)
        """
        self.fac = [1, 1]  # fac : 階乗(1!,2!,3!,...)
        self.factorial_max = factorial_max + 1
        self.finv = [1, 1] # inv : 逆元(1,1/2,...1/N) -> inv[i] = pow(i, MOD - 2, MOD) # フェルマーの小定理より
        self.inv = [0, 1]  # finv: 階乗の逆元(1/1!, 1/2!, 1/3!...)
        self.mod = mod
        self._build()

    def _build(self):
        for i in range(2, self.factorial_max):
            self.fac.append(self.fac[i - 1] * i % self.mod)
            self.inv.append(self.mod - self.inv[self.mod % i] * (self.mod // i) % self.mod)
            self.finv.append(self.finv[i - 1] * self.inv[i] % self.mod)

    def nCr(self, n: int, r: int):
        """
        O(1)
        """
        if n < r: return 0
        if n < 0 or r < 0: return 0
        return self.fac[n] * (self.finv[r] * self.finv[n - r] % self.mod) % self.mod
        
    def nHr(self, n: int, r: int):
        """
        ◯◯◯◯|◯◯|◯ ← これ系の問題。
        * n : 仕切り版の数 + 1
        * r : 分配する物自体の数
        
        * 区別のない r 個の物を n グループに分配する。
        eg.) 5個のボールを2個の箱に分配する分け方 : 2H5
        * n 種類の物から重複を許して r 個選択する。
        eg.) 3種類の果物から4個選ぶ取り方 : 3H4
        
        O(1)
        """
        print("**** factorial_maxの最大値としてn + rが必要となる! ****")
        return self.nCr(n - 1 + r, r)


def solve(r: "List[int]", c: "List[int]"):
    r1, r2 = r[0], r[1]
    c1, c2 = c[0], c[1]
    r2 += 1
    c2 += 1
    com = Combination(2 * (10 ** 6 + 1), MOD)
    ans = com.nCr(r1 + c1, c1) - com.nCr(r2 + c1, c1) - com.nCr(r1 + c2, c2) + com.nCr(r2 + c2, c2)
    print(ans % MOD)
    # 1  4 10 20  
    # 1  3  6 10
    # 1  2  3  4   
    # 1  1  1  1
    #   r1  r2
    
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    r = [int()] * (2)  # type: "List[int]"
    c = [int()] * (2)  # type: "List[int]"
    for i in range(2):
        r[i] = int(next(tokens))
        c[i] = int(next(tokens))
    solve(r, c)

if __name__ == '__main__':
    main()
