#!/usr/bin/env python3
import sys


def solve(T: int, N: "List[int]", M: "List[int]", A: "List[int]", B: "List[int]"):
    return


# Generated by 2.6.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    T = int(next(tokens))  # type: int
    N = [int()] * (T)  # type: "List[int]"
    M = [int()] * (T)  # type: "List[int]"
    A = [int()] * (T)  # type: "List[int]"
    B = [int()] * (T)  # type: "List[int]"
    for i in range(T):
        N[i] = int(next(tokens))
        M[i] = int(next(tokens))
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
    solve(T, N, M, A, B)

if __name__ == '__main__':
    main()
