#!/usr/bin/env python3
import sys


def solve(N: int, M: int, S: "List[str]"):
    ans = 0
    for i in range(N):
        for j in range(i + 1, N):
            for num in range(M):
                if S[i][num] == "x" and S[j][num] == "x":
                    break
            else:
                ans += 1
    print(ans)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    S = [next(tokens) for _ in range(N)]  # type: "List[str]"
    solve(N, M, S)

if __name__ == '__main__':
    main()
