#!/usr/bin/env python3
import sys
sys.setrecursionlimit(500 * 500)

YES = "Yes"  # type: str
NO = "No"  # type: str

# Generated by 2.6.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    H, W = map(int, input().split())
    field = []
    seen = []
    for _ in range(H):
        field.append(input())
        seen.append([0] * W)
    def dfs(x, y):
        # 終了条件
        if x < 0 or y < 0 or x >= W or y >= H or field[y][x] == "#" or seen[y][x] == 1:
            return False
        if field[y][x] == "g":
            return True
        # カウントアップ条件
        seen[y][x] = 1
        # 次の探索(分岐)
        for dx, dy in [(0, 1), (0, -1), (1, 0), (-1, 0)]:
            if dfs(x + dx, y + dy):
                return True
        return False

    for hh in range(H):
        for ww in range(W):
            if field[hh][ww] == "s":
                print(YES if dfs(ww, hh) else NO)
                # print(seen)
                return

if __name__ == '__main__':
    main()
