#!/usr/bin/env python3
import sys


def solve(X: int, Y: int):
    if Y == 0:
        print("ERROR")
        return
    l = X / Y
    s = str(l)
    p, q = s.split(".")
    if len(q) < 3:
        print(p + "." + q + "0" * (2 - len(q)))
    else:
        print(p + "." + q[:2])
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    X = int(next(tokens))  # type: int
    Y = int(next(tokens))  # type: int
    solve(X, Y)

if __name__ == '__main__':
    main()
