#!/usr/bin/env python3
import sys

def solve(S: str):
    must = set()
    ng = set()
    for i in range(10):
        if S[i] == "o":
            must.add(str(i))
        elif S[i] == "x":
            ng.add(str(i))
    ans = 0
    for num in range(10000):
        k = set(f"{num:0=4}")
        if k >= must and not k & ng:
            ans += 1
    print(ans)
    return


# Generated by 2.3.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
