#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, a: "List[int]"):
    p1, p2, p4 = 0, 0, 0
    for aa in a:
        if aa % 4 == 0:
            p4 += 1
        elif aa % 2 == 0:
            p2 = 1
        else:
            p1 += 1
    if p2 == 1:
        if p4 >= p1:
            print(YES)
        else:
            print(NO)
    else:
        if p4 + 1 >= p1:
            print(YES)
        else:
            print(NO)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    a = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, a)

if __name__ == '__main__':
    main()
