#!/usr/bin/env python3
import sys


def solve(S: str, T: str):
    S = S + "#"
    c = 1
    for ss, tt in zip(S, T):
        # print(ss, tt)
        if ss != tt:
            print(c)
            return
        c += 1
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    T = next(tokens)  # type: str
    solve(S, T)

if __name__ == '__main__':
    main()
