#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str
from collections import Counter

def solve(W: int, B: int):
    l = "wbwbwwbwbwbw" * 100
    for i in range(len(l)):
        d = Counter(l[i:(i + W + B)])
        if d["w"] == W and d["b"] == B:
            print(YES)
            return
    print(NO)
    return


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    W = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    solve(W, B)

if __name__ == '__main__':
    main()
