#!/usr/bin/env python3
import sys


def solve(all: int, N: int, M: int, L: "List[int]", x: "List[int]", y: "List[int]"):
    return


# Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    all = int(next(tokens))  # type: int
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    L = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    x = [int()] * (M)  # type: "List[int]"
    y = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        x[i] = int(next(tokens))
        y[i] = int(next(tokens))
    solve(all, N, M, L, x, y)

if __name__ == '__main__':
    main()
