#!/usr/bin/env python3
import sys


def solve(N: int, X: int):
    p, q = divmod(X, N)
    if q != 0:
        print(chr(ord("A") + p))
    else:
        print((chr(ord("A") + p - 1)))
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    solve(N, X)

if __name__ == '__main__':
    main()
