#!/usr/bin/env python3
from collections import deque

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    Q = int(input())
    l = deque()
    for _ in range(Q):
        t, *args = map(int, input().split())
        if t == 1:
            x, c = args[0], args[1]
            if len(l) > 0:
                val, count = l.pop()
                if val == x:
                    l.append((x, count + c))
                else:
                    l.append((val, count))
                    l.append((x, c))
            else:
                l.append((x, c))
        else:
            ans = 0
            x = args[0]
            while x > 0:
                val, count = l.popleft()
                ans += min(x, count) * val
                if x >= count:
                    x -= count
                else:
                    l.appendleft((val, count - x))
                    x = 0
            print(ans)
    return
            

if __name__ == '__main__':
    main()
