#!/usr/bin/env python3
import sys


def solve(p: str, q: str):
    p = ord(p) - ord("A")
    q = ord(q) - ord("A")
    if p > q:
        p, q = q, p
    
    acc = [0, 3, 4, 8, 9, 14, 23]
    print(acc[q] - acc[p])


    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    p = next(tokens)  # type: str
    q = next(tokens)  # type: str
    solve(p, q)

if __name__ == '__main__':
    main()
