#!/usr/bin/env python3
import sys

MOD = 1000000007  # type: int

def solve(S: str):
    T = "chokudai"
    M = len(S) + 1
    N = len(T) + 1
    dp = [[0 for _ in range(M)] for _ in range(N)]
    for j in range(M):
        dp[0][j] = 1
    
    for i in range(1, N):
        for j in range(1, M):
            if T[i - 1] == S[j - 1]:
                # j文字目を取る場合と足らない場合を選べる
                dp[i][j] = (dp[i - 1][j - 1] + dp[i][j - 1]) % MOD
            else:
                # j文字目を取らない選択しかない
                dp[i][j] = dp[i][j - 1] % MOD
    print(dp[-1][-1])

    return


# Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
